name: Slim CI

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Go version
        run: go version
        working-directory: slim

      - name: Go mod download
        run: go mod download
        working-directory: slim

      - name: Test ./...
        run: go test ./...
        working-directory: slim

  bench:
    name: Benchmarks
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Go mod download
        run: go mod download
        working-directory: slim

      - name: Run benchmarks (short)
        run: |
          go test -run=^$ -bench . -benchmem -benchtime=100x
        working-directory: slim
