name: Slim CI

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Go version
        run: go version

      - name: Go mod download
        run: go mod download

      - name: Build examples (compile only)
        run: go build ./examples/...

      - name: Test ./...
        run: go test ./...

  bench:
    name: Benchmarks
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Go mod download
        run: go mod download

      - name: Run benchmarks (short)
        run: |
          # Run a subset of fast, non-parallel benchmarks to avoid CI hangs
          go test -run=^$ -bench '^BenchmarkRouter_|^BenchmarkResponse_' -benchmem -benchtime=20x -count=1 -timeout=2m
